### ISSUE TITLE
How i can install on windows?

### ISSUE THREAD

**Issue by TheOppaiDragon** [Elagoht/VideoSizeReducer#1]
I see you done for linux but i have windows how i can install?

**Comment by Elagoht** [comment]
This package was created for Nemo file manager on linux. So you can't use it on Windows. But you can use main functionality of this package by using this command:

```cmd
ffmpeg -i input.mp4 -vcodec libx264 -crf 24 output.mp4
```

Of course you need to install ffmpeg first.
